### ISSUE TITLE
Is there a simpler way to debug textual apps?

### ISSUE THREAD

**Issue by Emasoft** [Textualize/textual-dev#13]
I'm using an environment where I cannot really run multiple instances of the terminal, so using textual console to debug the textual apps is not feasible. I tried many tricks, but nothing works.
Is there a simpler way to debug textual apps? 
I just need to save a detailed app.log file on disc and check it to find what went wrong. Since the issue is that we cannot write debug text on screen because it would broke the visual formatting, just redirecting all logging and errors output to a file log would be enough. Of course this log file would need to be ANSI formatted, and would require a textual powered reader to read it.
The local() method is great to print the local variables state at every log() or print() command, but its output should be integrated in a nicely ANSI formatted log file saved to disc. Or even better, textual-dev could include a reader app for ansi-encoded files, like the syntax aware codebrowser example app, so you can read a log with the full rich content generated by TextualHandler and RichHandler.
Is saving a rich log file possible? It would help to debug textual apps a lot for people like me.  What do you think?

**Comment by willmcgugan** [comment]
You can set the env var `TEXTUAL_LOG=textual.log` to dump the console output. You could also use the logging module from the standard library.

We could also add a option to set the IP address for the console, so you could run it on another machine on your network.

**Comment by Emasoft** [comment]
@willmcgugan Thanks! I tried enabling the env var TEXTUAL_LOG, and it works. But there are some issues:  
  
  * 1. The output log is in plain text, not ansi coloured at all
  * 2. There are no Tracebacks rich style
  * 3. There are no Locals rich style
  * 4. no errors or messages are reported when I try to push a screen outside of the main App with this line: `    main_application.push_screen(table_select_screen, book_choice_callback)`. Notice that table_select_screen is just an instance of the DataTableRenderables example class Iwith Screen instead of App as base class), but the issue appears on all screen classes I try to push.  
  * 5. No line of code reported even if I used `(%(funcName)s(%(lineno)d))` in the formatter string.
  
This is my code for logger setup:
```python
def setup_console_logger(console:Console, debug_threads:bool=True, debug_on:bool=True):
    
    DEBUG_ON = (os.getenv('DEBUG', default='False').lower() in ('true', '1', 't'))
        
    LOG_FORMAT = "%(message)s"
    LOG_DIR = Path.cwd()
    LOG_FILE = "books_manager.log"
    TEXTUAL_LOG_FILE = "my_textual.log"
    set_env_variable("TEXTUAL_LOG", TEXTUAL_LOG_FILE )
    set_env_variable("TEXTUAL_DEBUG", 'True' )

    LOG_LEVEL = logging.NOTSET
    LOG_DATE_FMT= "[%X]"
    LOG_FILE_MODE = 'a'
    LOG_ENCODING = 'utf-8'
            
    def get_file_handler(log_dir: Path, log_filename: str):
        log_format = f"%(asctime)s - [%(levelname)s] - %(name)s - (%(funcName)s(%(lineno)d)) - %(message)s"
        log_file = log_dir / log_filename
        file_handler = logging.FileHandler(log_file)
        file_handler.setFormatter(logging.Formatter(log_format))
        return file_handler
    
    
    def get_rich_handler(console: Console):
        #rich_format = f"%(message)s"
        rich_format = f"%(asctime)s - [%(levelname)s] - %(name)s - (%(funcName)s(%(lineno)d)) - %(message)s"
        rh = RichHandler(rich_tracebacks=True, console=console)
        rh.setFormatter(logging.Formatter(rich_format))
        return rh
    
    def get_textual_handler(console: Console):
        textual_format = f"%(asctime)s - [%(levelname)s] - %(name)s - (%(funcName)s(%(lineno)d)) - %(message)s"
        th = TextualHandler(stderr = True, stdout = True)
        th.setFormatter(logging.Formatter(textual_format))
        return th
    
    def get_logger(log_dir: Path, log_filename: str, console: Console):
        logger = logging.getLogger('my_textual_app')
        logger.setLevel(logging.NOTSET)
        logger.addHandler(get_file_handler(log_dir, log_filename))
        logger.addHandler(get_rich_handler(console))
        logger.addHandler(get_textual_handler(console))
        logger.propagate = False
        return logger
        
    def setup_queue_handler(active_logger):
        que = queue.Queue(-1)  # no limit on size
        queue_handler = QueueHandler(que)
        handler = logging.StreamHandler()
        listener = QueueListener(que, handler)
        #root_log = logging.getLogger()
        #root_log.addHandler(queue_handler)
        active_logger.addHandler(queue_handler)
        formatter = logging.Formatter('%(threadName)s: %(message)s')
        handler.setFormatter(formatter)
        listener.start()
        
    active_logger=None
    if debug_on:
        active_logger = get_logger(LOG_DIR, LOG_FILE, console)
        if debug_threads:
            setup_queue_handler(active_logger)
        install(show_locals=True)
        active_logger.info("Logging of app started!")
        
    return active_logger
    
    
```
----

I call this with:

```python
def main():
    global main_application
    global tex_log

    main_application = MainApp()
    tex_log = setup_console_logger(console=main_application.console, debug_threads=True, debug_on=True)
        tex_log.debug("Starting Main Application...")
        main_application.run()
```

**Comment by willmcgugan** [comment]
The output log is plain text, yes. It's not going to write escape sequences, which is bad idea generally, since they aren't portable. The next version of Textual will add a `--host` option so you can connect to a `textual console` on another machine, which will give you Rich formatting.
