### ISSUE TITLE
Add a --host switch to `textual run` command

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual-dev#14]
We need to had a `--host` switch to the `textual run` command which will connect to the given host. At the moment, this defaults to `127.0.0.1`, but the switch would allow the console to run on another machine.

Textual (in main) has a `TEXTUAL_DEVTOOLS_HOST` env var which defaults to `127.0.0.1`, `textual_dev` should populate this env var in the `textual run` command.

**Comment by rodrigogiraoserrao** [comment]
> `textual_dev` should populate this env var in the `textual run` command.

What does this mean?

**Comment by willmcgugan** [comment]
`textual run` launches a process for the textual app, with a number of environment variables. The new `TEXTUAL_DEVTOOLS_HOST` should go in those env vars.

**Comment by rodrigogiraoserrao** [comment]
Thanks. Shouldn't `textual run` also get the `--host` option, though?
I'm assuming we may want to attach a running app to a console that is on another machine, in which case the environment variable in the machine where `textual run` is used can't be set by the command `textual console --host ...` that was ran in _another_ machine.

**Comment by willmcgugan** [comment]
Yes, my mistake. the switch belongs on `textual run`

**Comment by willmcgugan** [comment]
@rodrigogiraoserrao Has there been any work done on this? I don't see a PR.

**Comment by rodrigogiraoserrao** [comment]
#16 has been around for a while. It lacked a Textual update which has now been pushed.
