### ISSUE TITLE
Add support for detecting `rio` in `textual diagnose`

### ISSUE THREAD

**Issue by davep** [Textualize/textual-dev#17]
It looks like [rio](https://github.com/raphamorim/rio) doesn't currently advertise itself via `TERM_PROGRAM` or via any other obvious environment variable. The result is it comes out as `*Unknown*`.

It looks like `XPC_SERVICE_NAME` is always set (on macOS anyway) to something that starts with `application.com.raphaelamorim.rio` so this can work as a fallback detection method.

**Comment by willmcgugan** [comment]
Rio looks like one to watch. Maybe you could also post an issue on their repo asking for `TERM_PROGRAM` to be set?

**Comment by davep** [comment]
@willmcgugan Yeah, I've discovered a few issues with it in my brief play this morning, so I was going to take some time this weekend, hopefully, to drive in and make notes and then issue somethings (see also function keys seemingly not working, line characters not performing well, some characters not lining up well, screens not fully drawing often, etc...).

**Comment by davep** [comment]
Raised this specific one as https://github.com/raphamorim/rio/issues/200

**Comment by davep** [comment]
No longer necessary as support for `TERM_PROGRAM` has now been added to rio.
