### ISSUE TITLE
Textual Serve (1.1.0) gets 403 status codes trying to access resources with Linux

### ISSUE THREAD

**Issue by bapainter** [Textualize/textual-dev#37]
Textual serve shows 403 (forbidden) http status codes once it has launched.  If I try to access the app via the browser, I only see the Textual logo.  The logs displayed on the terminal show that certain resources cannot be accessed.  

![image](https://github.com/user-attachments/assets/dad7cfc7-7cd4-480f-8f6c-304ececef9c5)

The problem seems to be the double forward slashes in the resource address (see image).  If I enter the resource address in the browser, I get the forbidden message, however, if I remove a slash, it accesses the resource correctly.  Based on other users comments on the Textual Discord server, this issue also happens with Ubuntu and may just be related to Linux.  

Versions:
 - Textual: 0.79.0
 - Textual-serve: 1.1.0
 - Python: 3.12.5
 - Linux: EndeavourOS (kernel 6.10.7)

**Comment by willmcgugan** [comment]
What version of aiohttp do you have installed?

**Comment by bapainter** [comment]
Pip says....

aiohttp                3.10.5
aiohttp-jinja2         1.6

**Comment by EstebanMunoz** [comment]
I'm having the same problem in Windows.

- Textual: 0.79.1
- Textual-serve: 1.1.0
- aiohttp 3.10.5
- aiohttp-jinja2 1.6
- Python: 3.12.4
- Windows 11

**Comment by willmcgugan** [comment]
Wrong repo, bit this was fixed in textual-serve
