### ISSUE TITLE
pypi releases

### ISSUE THREAD

**Issue by 0-wiz-0** [Textualize/textual-dev#40]
This repository has tags for 1.5.1 and 1.7.1
On pypi, the latest I can find is 1.7.0.
Can you please release 1.7.1 on pypi?
Bonus points for tagging the other pypi releases in this repository, at least the recent ones like 1.6.x and 1.7.0.
Thank you!

**Comment by willmcgugan** [comment]
There is no 1.7.1, the release number was an error.
